beam:
  rest:
    swagger-open: true  #是否开启swagger
    auth-open: true #拦截器是否开启
    sign-open: true #签名机制是否开启
    secret: miyao        #秘钥
server:
  port: 8081
  servlet:
    context-path: /beam_rest
spring:
  profiles:
    active: @spring.active@
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB

---
#开发环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/beam?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000 #超时时间（毫秒）
log:
  path: /home/beam/rest/local

---
#测试环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
log:
  path: /home/beam/rest/dev

---
#生产环境
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
log:
  path: /home/beam/rest/pro
