beam:
  admin:
    swagger-open: true  #是否开启swagger
    captcha-open: true #是否开启登陆验证码
    redis-open: true  # 是否开启redis缓存
    shiro-redis: true # 是否开启shiro session存到redis里
server:
   port: 8080
   servlet:
     context-path: /beam_admin
spring:
  profiles:
    active: @spring.active@
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB

---
#开发环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 8
      min-idle: 1
      max-active: 20
      max-wait: 60000
      validation-query: select 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000 #超时时间（毫秒）
log:
  path: /home/beam/admin/local

---
#测试环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
log:
  path: /home/beam/admin/dev

---
#生产环境
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000
log:
  path: /home/beam/admin/pro