beam:
  admin:
    swagger-open: true  #是否开启swagger (true/false)
    captcha-open: true
    redis-open: true  # 是否开启redis缓存  true开启   false关闭
    shiro-redis: true # true表示shiro session存到redis里，需要开启redis，才会生效【分布式场景】
    version: 0.0.1
server:
   port: 8080
   servlet:
     context-path: /beam_ht
spring:
  servlet:
    multipart:
      max-file-size: 512MB
      max-request-size: 1024MB
  profiles:
    active: @spring.active@

---
#开发环境
spring:
  profiles: local
  datasource:
    url: jdbc:mysql://localhost:3306/beam?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password: 123456
    timeout: 6000ms
log:
  path: /home/beam/local
ftp:
  host: 152.136.219.223
  port: 21
  username: uftp
  password: 123456
  img-path: img/
  video-path:  video/
  course-path: course/

---
#测试环境
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms
log:
  path: /home/beam/dev

---
#生产环境
spring:
  profiles: pro
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/beam?autoReconnect=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=CONVERT_TO_NULL&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    filters: log4j,wall,mergeStat
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 6000ms
log:
  path: /home/beam/pro